import { Inter } from 'next/font/google'
import '@/styles/globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer'
import Provider from '@/components/Provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Quest IT',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <main className='app bg-gray-100'>
            <Navbar />
            {children}
            <Footer/>
          </main>
        </Provider>
      </body>
        
    </html>
  )
}
